scopes:

    group:
        label: Groups
        type: group
        modelClass: Publipresse\Forms\Models\Record
        options: filterGroups
        conditions: "`group` in (:filtered)"

    created_at:
        label: Created at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'